"""Uppgiftsklasser för EM-visualiseringsprogrammet, samlade per kapitel.

Denna paketstruktur ersätter den tidigare enda filen problems.py. Varje
kapitelmodul (ch02..ch10) innehåller uppgiftsklasserna för motsvarande
kapitel i kursboken, i samma ordning som de dyker upp i menyn. Allt som
tidigare gjordes med 'from .problems import *' fungerar oförändrat eftersom
det här paketet samlar upp och exponerar alla klasser på samma sätt.
"""

from .ch02 import (
    ChargedSpheresSmallAngle,
    ChargedRingAxis,
    FiniteLineCharge2D,
    SemiCircularSurfaceAxis,
    SphericalShellPotential,
    ConcentricChargedCylinders,
    SphericalCapacitorDesign,
    ConcentricSphericalShells,
    AtmosphericChargeDensity,
    OffsetCavitySphereExterior,
    CoaxialCylinderVoltage,
    SphericalConductorBreakdown,
    CoaxialTubeSpaceCharge,
    RadialChargeSphere,
    InsertedMetalPlateCapacitor,
    UniformSpaceChargePlates,
)
from .ch03 import (
    HClDipoleField,
    PorcelainSlabCapacitor,
    GroundedInnerSphereChargeSplit,
    ChargedDielectricShell,
    DielectricFilledSphericalGap,
    MakrofolCapacitorDesign,
    CoaxialTwoDielectricCapacitance,
    BreakdownVoltageCases,
    DielectricSlabCapacitor,
    ElectretCylinderAxis,
    ObliqueConductorDielectricBoundary,
)
from .ch04 import (
    SphericalShellChargingEnergy,
    ParallelPlateForceDistance,
    CopperFoilLevitationEbonite,
    ThundercloudEnergyEstimate,
    CylindricalCapacitorDielectricPullIn,
    PointChargeConductingPlane,
)
from .ch05 import (
    ConductiveCoaxialElectrodes,
    CoaxialCableLeakage,
    VariableSigmaCoaxialElectrolyte,
    SemicylindricalRingResistor,
    SteadyCurrentInterfaceCharge,
)
from .ch06 import (
    FiniteWireBiotSavart,
    SquareLoopOnAxis,
    RightAngleWireCorner,
    ThinCurrentStripField,
    CircularArcOnAxis,
    RotatingChargedDisk,
)
from .ch07 import (
    ElectronOrbitDipoleMoment,
    CircularLoopTorqueUniformField,
    DipoleDipoleTorque,
    LoopDipoleApproximationError,
    AntarcticIceFlux,
    CopperWireMagneticLevitation,
    InfiniteWireRectangularLoopFlux,
)
from .ch08 import (
    PermanentMagnetAirGapBHCurve,
    NonlinearIronMagneticCircuit,
    MagneticBridgeCircuit,
    CurrentCarryingMagneticTube,
    HorseshoeMagnetAnchorForce,
    PermanentlyMagnetizedCylinderAxis,
    MagnetizationCurrentsCylinder,
)
from .ch09 import (
    MutualInductanceParallelWiresSquare,
    MutualInductanceCoaxialLoops,
    OpenSecondaryTransformerVoltage,
    MovingLoopFieldWork,
    MovingLoopDipoleEmf,
)
from .ch10 import (
    DisplacementCurrentCapacitor,
    RadialChargeExpansionMaxwellTest,
)

__all__ = [
    'ChargedSpheresSmallAngle',
    'ChargedRingAxis',
    'FiniteLineCharge2D',
    'SemiCircularSurfaceAxis',
    'SphericalShellPotential',
    'ConcentricChargedCylinders',
    'SphericalCapacitorDesign',
    'ConcentricSphericalShells',
    'AtmosphericChargeDensity',
    'OffsetCavitySphereExterior',
    'CoaxialCylinderVoltage',
    'SphericalConductorBreakdown',
    'CoaxialTubeSpaceCharge',
    'RadialChargeSphere',
    'InsertedMetalPlateCapacitor',
    'UniformSpaceChargePlates',
    'HClDipoleField',
    'PorcelainSlabCapacitor',
    'GroundedInnerSphereChargeSplit',
    'ChargedDielectricShell',
    'DielectricFilledSphericalGap',
    'MakrofolCapacitorDesign',
    'CoaxialTwoDielectricCapacitance',
    'BreakdownVoltageCases',
    'DielectricSlabCapacitor',
    'ElectretCylinderAxis',
    'ObliqueConductorDielectricBoundary',
    'SphericalShellChargingEnergy',
    'ParallelPlateForceDistance',
    'CopperFoilLevitationEbonite',
    'ThundercloudEnergyEstimate',
    'CylindricalCapacitorDielectricPullIn',
    'PointChargeConductingPlane',
    'ConductiveCoaxialElectrodes',
    'CoaxialCableLeakage',
    'VariableSigmaCoaxialElectrolyte',
    'SemicylindricalRingResistor',
    'SteadyCurrentInterfaceCharge',
    'FiniteWireBiotSavart',
    'SquareLoopOnAxis',
    'RightAngleWireCorner',
    'ThinCurrentStripField',
    'CircularArcOnAxis',
    'RotatingChargedDisk',
    'ElectronOrbitDipoleMoment',
    'CircularLoopTorqueUniformField',
    'DipoleDipoleTorque',
    'LoopDipoleApproximationError',
    'AntarcticIceFlux',
    'CopperWireMagneticLevitation',
    'InfiniteWireRectangularLoopFlux',
    'PermanentMagnetAirGapBHCurve',
    'NonlinearIronMagneticCircuit',
    'MagneticBridgeCircuit',
    'CurrentCarryingMagneticTube',
    'HorseshoeMagnetAnchorForce',
    'PermanentlyMagnetizedCylinderAxis',
    'MagnetizationCurrentsCylinder',
    'MutualInductanceParallelWiresSquare',
    'MutualInductanceCoaxialLoops',
    'OpenSecondaryTransformerVoltage',
    'MovingLoopFieldWork',
    'MovingLoopDipoleEmf',
    'DisplacementCurrentCapacitor',
    'RadialChargeExpansionMaxwellTest',
]
